# Generated by Django 3.2.4 on 2022-01-23 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_allotment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allotment',
            options={'ordering': ['preference']},
        ),
    ]
