# Generated by Django 3.2.4 on 2022-01-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_student_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hostel_fees',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='mess_fees',
            field=models.BooleanField(default=False),
        ),
    ]
