# Generated by Django 3.2.4 on 2022-01-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220122_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
                ('category', models.CharField(choices=[('VEG', 'VEG'), ('NON-VEG', 'NON-VEG')], max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='attendance',
            field=models.CharField(default='000.000', max_length=10),
        ),
    ]
